---
title: "Medicare 2015 Notes"
author: "Abhijit Dasgupta"
output: 
  html_notebook:
    includes:
      in_header: header.html
---


# Introduction

This study seeks to understand why rates of primary knee replacements vary across geographical 
regions. There are 306 geographical regions in this study, with the rate of knee replacement varying
from 4/1000 to 14/1000. This study covers the years 2011-2015, for a total of 147M records (about 35M 
patients), with one record per person-year. 

Earlier studies have attempted to look at this data standardized for age, sex, and race, and 
have still found variability in the incidence rates. The tacit assumption that was made in earlier 
studies is that the rate of osteoarthritis (OA) of the knee is uniform across the country. 

The obvious criticism of earlier findings is that there are unmeasured confounders that would account
for the variability. This study attempts to incorporate many of the confounders to see if they can
account for the observed variability adequately. These confounders include comorbidities (affects the
risk of getting a replacement), healthcare utiliization variables (do people differ in going to the
doctor due to differences in access or attitudes), and physician attitudes (captured by % with Medicare
Avantage HMO, which can have spillover attitudinal effects on doctors[^1], and availability of 
orthopedic surgeons).

The most common reason for knee replacement is osteoarthritis (OA) of the knee, which is a repeated
use degenerative disorder, so the incidence of OA can be related to occupation. This should be 
captured in the `physjob_t_wtperc` variable at least at the region level.

# Data
The individual level identifier is `bene_id`. There are 20 comorbidities captured each year of a patient's
participation in the study. Person-years exposed is captured in the `Personyrs` variable. 

+ Region ids `hrr` have 306 unique values, but are not sequential
+ Once a patient reaches 2 replacements (either 1+1 or 2), they should have 0 replacements in the 
following years, since we're only looking at primary replacements and not revisions. 
+ `poor` is defined as also being on Medicaid

# Code

### Subsetting data

We'll start developing models on a subset of the data, say on 1M subjects. This is to ensure that
we can iterate on code quickly without waiting 2 days for code to run. To do this, Mike suggests using
`PROC SURVEYSELECT`

```sas
proc surveyselect data=sh026544.project4_hrr_end15 out=sh026544.project4_hrr_end15_sampled 
    noprint method=srs sampsize = 1000000 seed=3589;
  cluster bene_id;
  run;
```

### Analysis

I feel that the outcome measure is really distributed as Bin(2,p), rather than a Poisson. In fact, 
theory would suggest that the Poisson would not be a good approximation to the Binomial in this case,
so I'd be reluctant to use a Poisson model on this. 

I've been thinking that a better first analysis is to look at the rate of primary replacement with
covariates. This can avoid the issue having correlated binary outcomes without sufficient information
to analyze it. A potential twist would be to include a covariate whether other leg was already replaced,
which would be a modifier for the risk of replacement. If bilateral replacement happens, it is still 
just counted once as a replacement event; a secondary analysis can be done whether bilateral replacements
are more likely under certain person/environment combinations. 

The workhorse for this analysis will be `PROC GLIMMIX`, or potentially `PROC GENMOD` if we go towards
GEE analysis. However, for having multilevel covariates, `GLIMMIX` might be the better option. 


[^1]: Doctors who have a lot of patients in Medicare Advantange, which is a managed care HMO, tend to
be influenced by that culture which promotes lower cost treatments. This attitude often can spill over
to the fee-for-service general Medicare population, which would then tend to get more conservative,
lower cost treatment. 
