---
title: "Understanding the data design and simulation"
author: "Abhijit"
# date: February 27, 2019
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    #toc_float: true
    theme: united
    highlight: haddock
    md_extensions: +definition_lists
    pandoc_args: [
      "--syntax-definition","sas.xml"]
    standalone: true
    self_contained: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

# Data description

The physician characteristics are obtained as aggregate ecological measures like

- Percentage with Medicare Advantage (`Mcare_adv_wtperc`)
- Density of orthopedic surgeons (`Ortho_per_100000`)

There are also some ecological measures for patient characteristics:

- % obesity (`obese_wtperc`)
- % with physical occupation (`physjob__wtperc`)
- % smokers (`smoking_wtperc`)

At the patient level we have

- Age (continuous, `age_at_end_ref_yr`, discrete, `agecat`)
- Gender (`Male`, 1=male, 0=female)
- Race (`Race`, categorized as 1=white, 2=black, 3=hispanic, 4=asian, 5=other)
- A listing of 20 comorbidities, as 0/1 variables
- knee OA visits (continuous, `koa_visits`, discrete, `koa`, 0/1)
- knee symptom visits (continous, `kneesymptom_visits`, discrete, `kneesymptoms`, 0/1)
- Total knee visits (continuous, `allkneevisits`, discrete, `knee_patient`, 0/1)
- Dead or alive (`dead`, 1 = dead in year)
- Time of followup during calendar year (`personyrs`, 0-1 yrs)
- Current year of observation (`bene_enrollmt_ref_yr`, 2011-2015)
- Poor or on Medicaid (`poor`, 0/1)

We also have two variables that are based on ZCTA's, rather than the actual 
HRR's. [Dartmouth](http://archive.dartmouthatlas.org/tools/downloads.aspx?tab=39){target="_blank"} provides a translation from ZIP codes to HRR, so these scores 
can be translated to HRR data.

- Socio-economic status (`zscore`)
- Rural district (`rural`, 0/1)

# The conceptual model

The underlying conceptual model that Mike proposes is

```
rate = [patient characteristics] + [physician characteristics] + [behavioral characteristics] + error
```

The part we're interested here is in the physician characteristics, with the
behavioral characteristics being nuisance, in some sense. 


### Biology and patient characteristics

1. Severity of knee condition
  ~ This would look at the number of knee-related visits, using `koa_visits`, 
    `kneesymptom_visits` or `allkneevisits`. These might vary by year as the 
    knee conditions progress or improve. This might also be normalized with 
    time of follow-up to get an overall sense of severity. 

1. Demographics
  ~ Older people, or people of a certain race, may be differentially prone to get
  a transplant. This effect may be confounded by socio-economic status, rural/urban
  divide, or if they are poor.
  
1. Comorbidities
  ~ We might like to create a comorbidity score as the number of comorbidities
  present, with the idea that more morbid patients might be less likely to
  receive transplants. There may be an issue with recency of the comorbidity:
  `acutemi`, `afib`, `ckd`, `depress`,`diab`,`ulcers` are all measuring recent
  incidence, while the others reflect a history (ever happened). `hiv` might
  just be an issue anytime because of surgery, as will `stroke` and `liver`.
  Comorbidities (or hypochondria) severity might be indicated by `op_visits`,
  the number of outpatient visits the patient made. Obesity (`obese_wtperc`) is
  only available as an aggregate percentage in the HRR, so might be of limited
  value. It may also influence local physician/patient behavior, if one sees
  more obese patients or a relatively healthier population. 

1. Proximity to death
  ~ If someone is about to die, they are more unlikely to get a transplant. This 
  can be quantified as odds of getting a transplant if patient died that year, 
  or the following year.
  
1. Previous transplant
  ~ Having one knee replacement should increase the risk that you get the other 
  knee replaced. 

### Physician and local characteristics

Physician and local characteristics are perhaps confounded, since these are
available only in aggregate and not based on individual patient interactions.
We'll lump them together for this reason.

1. Aggregate demographics
  ~ Obesity, blue collar work and smoking are all available as aggregate
  percentage and can influence a local practitioner's behavior. It might be argued 
  that regions with high levels of obesity would induce certain kinds of processes
  to treat that population, compared with others with lower levels of obesity. However, 
  since we only have HRR-level information about this factors, their influence might
  not be as strong, since we can't assess the obesity/comorbidity relationships with 
  age, sex and race directly. Similarly, with blue-collar work, we expect more wear-and-tear
  among physical laborers, and also the need to be up and running (literally) may
  promote earlier replacements so fewer work days are lost. 
  
1. Local economics
  ~ Rural districts (`rural`) and poor districts (`zscore`) will certainly
  influence practitioners, both in quality and outlook. We can also get a sense
  of the SES of actual observed patients within a HRR by aggregating their poor
  status (`poor`). Poor, rural districts will typically have poorer access to 
  therapists and support paramedical professional that can be alternatives to 
  knee replacements.
  
1. Access to care
  ~ Access to orthopedic surgeons can be measured through `ortho_per_100000`,
  with more surgeons perhaps indicative of higher rates of replacements
  
1. Physician environment
  ~ The percentage with Medicare Advantage (`mcare_adv_wtperc`), which is a HMO,
  can be influencial since MA, which is a HMO, will promote lower cost
  alternatives like therapy to knee replacement.

### Behavioral and extraneous factors

These are basically unmeasured confounders, which might induce extra-Poisson
variability in the estimates.

# Data structure and study design

The data is a retrospective collection of Medicare data from 2011-2015. Patients
are followed multiple years, but data is only available on an annualized basis,
i.e., one record per patient per year. Patients may move, so they may be part of
different HRRs in different years. ( _Can they be part of different HRRs the
same year?_). We also have aggregate data on an annualized basis about the HRR
characteristics.

## Implications for analysis

1. If we consider the entire dataset together, we have repeated measures for
each patient, with potentially imperfect nesting within HRR. We also have
time-dependent covariates (like age, comorbidities, doctor visits, vital status,
SES, as well as HRR level covariates that can change). The repeated measures can
be handled within `PROC GEE` or `PROC GENMOD` with a `REPEATED` and a `WITHIN`
statement, but the time-dependent covariates pose a bit of a problem. We need to 
evaluate how much exposure to time-varying covariates and inperfect nesting 
exists. 

1. We can look at a year-by-year analysis first, looking at patterns consistent
over the years, and identifying local/physician factors that create outlier 
HRRs with respect to local characteristics, and how those drift over time. This 
allows the use of regular GLM models, without worrying about repeated measures.

1. Death is an interesting case. We probably need to create a variable per person
per year to see if the person died in the current or the following year, since
if death is proximate the chance that replacement occurs is lower. 

1. One of the basic questions to ponder is if we should add any interaction terms
to any model we use, specially interactions with year, to show drift over time, 
and interactions with gender or race.

1. We need to only use baseline age in any modeling, since otherwise age becomes
time-varying. 
